package br.telehand.model;

// Generated 28/03/2014 00:06:08 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbAgendaId generated by hbm2java
 */
@Embeddable
public class TbAgendaId implements java.io.Serializable {

	private int idJanela;
	private int idEquipe;

	public TbAgendaId() {
	}

	public TbAgendaId(int idJanela, int idEquipe) {
		this.idJanela = idJanela;
		this.idEquipe = idEquipe;
	}

	@Column(name = "Id_janela", nullable = false)
	public int getIdJanela() {
		return this.idJanela;
	}

	public void setIdJanela(int idJanela) {
		this.idJanela = idJanela;
	}

	@Column(name = "Id_equipe", nullable = false)
	public int getIdEquipe() {
		return this.idEquipe;
	}

	public void setIdEquipe(int idEquipe) {
		this.idEquipe = idEquipe;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbAgendaId))
			return false;
		TbAgendaId castOther = (TbAgendaId) other;

		return (this.getIdJanela() == castOther.getIdJanela())
				&& (this.getIdEquipe() == castOther.getIdEquipe());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdJanela();
		result = 37 * result + this.getIdEquipe();
		return result;
	}

}
