package br.telehand.model;

// Generated 28/03/2014 00:06:08 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbAgenda generated by hbm2java
 */
@Entity
@Table(name = "tb_agenda", catalog = "db_sge")
public class TbAgenda implements java.io.Serializable {

	private TbAgendaId id;
	private TbEquipe tbEquipe;
	private TbJanela tbJanela;
	private Date dtCriacao;
	private Date dtFim;
//	private Set tbAgendamentos = new HashSet(0);

	public TbAgenda() {
	}

	public TbAgenda(TbAgendaId id, TbEquipe tbEquipe, TbJanela tbJanela,
			Date dtCriacao) {
		this.id = id;
		this.tbEquipe = tbEquipe;
		this.tbJanela = tbJanela;
		this.dtCriacao = dtCriacao;
	}

	public TbAgenda(TbAgendaId id, TbEquipe tbEquipe, TbJanela tbJanela,
			Date dtCriacao, Date dtFim, Set tbAgendamentos) {
		this.id = id;
		this.tbEquipe = tbEquipe;
		this.tbJanela = tbJanela;
		this.dtCriacao = dtCriacao;
		this.dtFim = dtFim;
//		this.tbAgendamentos = tbAgendamentos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idJanela", column = @Column(name = "Id_janela", nullable = false)),
			@AttributeOverride(name = "idEquipe", column = @Column(name = "Id_equipe", nullable = false)) })
	public TbAgendaId getId() {
		return this.id;
	}

	public void setId(TbAgendaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_equipe", nullable = false, insertable = false, updatable = false)
	public TbEquipe getTbEquipe() {
		return this.tbEquipe;
	}

	public void setTbEquipe(TbEquipe tbEquipe) {
		this.tbEquipe = tbEquipe;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_janela", nullable = false, insertable = false, updatable = false)
	public TbJanela getTbJanela() {
		return this.tbJanela;
	}

	public void setTbJanela(TbJanela tbJanela) {
		this.tbJanela = tbJanela;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Dt_criacao", nullable = false, length = 0)
	public Date getDtCriacao() {
		return this.dtCriacao;
	}

	public void setDtCriacao(Date dtCriacao) {
		this.dtCriacao = dtCriacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Dt_fim", length = 0)
	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

//	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tbAgenda")
//	public Set<TbAgendamento> getTbAgendamentos() {
//		return this.tbAgendamentos;
//	}

//	public void setTbAgendamentos(Set<TbAgendamento> tbAgendamentos) {
//		this.tbAgendamentos = tbAgendamentos;
//	}

}
