package br.telehand.model;

// Generated 27/03/2014 16:20:36 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbBloqueioId generated by hbm2java
 */
@Embeddable
public class TbBloqueioId implements java.io.Serializable {

	private int idEquipe;
	private Date dtInicio;
	private Date dtFim;

	public TbBloqueioId() {
	}

	public TbBloqueioId(int idEquipe, Date dtInicio, Date dtFim) {
		this.idEquipe = idEquipe;
		this.dtInicio = dtInicio;
		this.dtFim = dtFim;
	}

	@Column(name = "Id_equipe", nullable = false)
	public int getIdEquipe() {
		return this.idEquipe;
	}

	public void setIdEquipe(int idEquipe) {
		this.idEquipe = idEquipe;
	}

	@Column(name = "Dt_inicio", nullable = false, length = 0)
	public Date getDtInicio() {
		return this.dtInicio;
	}

	public void setDtInicio(Date dtInicio) {
		this.dtInicio = dtInicio;
	}

	@Column(name = "Dt_fim", nullable = false, length = 0)
	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbBloqueioId))
			return false;
		TbBloqueioId castOther = (TbBloqueioId) other;

		return (this.getIdEquipe() == castOther.getIdEquipe())
				&& ((this.getDtInicio() == castOther.getDtInicio()) || (this
						.getDtInicio() != null
						&& castOther.getDtInicio() != null && this
						.getDtInicio().equals(castOther.getDtInicio())))
				&& ((this.getDtFim() == castOther.getDtFim()) || (this
						.getDtFim() != null && castOther.getDtFim() != null && this
						.getDtFim().equals(castOther.getDtFim())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEquipe();
		result = 37 * result
				+ (getDtInicio() == null ? 0 : this.getDtInicio().hashCode());
		result = 37 * result
				+ (getDtFim() == null ? 0 : this.getDtFim().hashCode());
		return result;
	}

}
