package br.telehand.model;

// Generated 27/03/2014 16:20:36 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbBloqueio generated by hbm2java
 */
@Entity
@Table(name = "tb_bloqueio", catalog = "db_sge")
public class TbBloqueio implements java.io.Serializable {

	private TbBloqueioId id;
	private TbEquipe tbEquipe;

	public TbBloqueio() {
	}

	public TbBloqueio(TbBloqueioId id, TbEquipe tbEquipe) {
		this.id = id;
		this.tbEquipe = tbEquipe;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idEquipe", column = @Column(name = "Id_equipe", nullable = false)),
			@AttributeOverride(name = "dtInicio", column = @Column(name = "Dt_inicio", nullable = false, length = 0)),
			@AttributeOverride(name = "dtFim", column = @Column(name = "Dt_fim", nullable = false, length = 0)) })
	public TbBloqueioId getId() {
		return this.id;
	}

	public void setId(TbBloqueioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_equipe", nullable = false, insertable = false, updatable = false)
	public TbEquipe getTbEquipe() {
		return this.tbEquipe;
	}

	public void setTbEquipe(TbEquipe tbEquipe) {
		this.tbEquipe = tbEquipe;
	}

}
