package br.telehand.model;

// Generated 27/03/2014 16:20:36 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbDadosClientes generated by hbm2java
 */
@Entity
@Table(name = "tb_dados_clientes", catalog = "db_sge")
public class TbDadosClientes implements java.io.Serializable {

	private Integer idCliente;
	private Integer cpf;
	private Integer cnpj;
	private String nmCliente;
	private String cdEmail;
	private Date dtAdmissao;
	private String endereco;
	private String numero;
	private String complemento;
	private String bairro;
	private String cidade;
	private String uf;
	private String pais;
	private String cep;
	private Long nrTel;
	private Long nrCelular;
	private String nrIdent;

	public TbDadosClientes() {
	}

	public TbDadosClientes(String nmCliente) {
		this.nmCliente = nmCliente;
	}

	public TbDadosClientes(Integer cpf, Integer cnpj, String nmCliente,
			String cdEmail, Date dtAdmissao, String endereco, String numero,
			String complemento, String bairro, String cidade, String uf,
			String pais, String cep, Long nrTel, Long nrCelular, String nrIdent) {
		this.cpf = cpf;
		this.cnpj = cnpj;
		this.nmCliente = nmCliente;
		this.cdEmail = cdEmail;
		this.dtAdmissao = dtAdmissao;
		this.endereco = endereco;
		this.numero = numero;
		this.complemento = complemento;
		this.bairro = bairro;
		this.cidade = cidade;
		this.uf = uf;
		this.pais = pais;
		this.cep = cep;
		this.nrTel = nrTel;
		this.nrCelular = nrCelular;
		this.nrIdent = nrIdent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_cliente", unique = true, nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "cpf", precision = 11, scale = 0)
	public Integer getCpf() {
		return this.cpf;
	}

	public void setCpf(Integer cpf) {
		this.cpf = cpf;
	}

	@Column(name = "cnpj", precision = 14, scale = 0)
	public Integer getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(Integer cnpj) {
		this.cnpj = cnpj;
	}

	@Column(name = "nm_cliente", nullable = false, length = 20)
	public String getNmCliente() {
		return this.nmCliente;
	}

	public void setNmCliente(String nmCliente) {
		this.nmCliente = nmCliente;
	}

	@Column(name = "cd_email")
	public String getCdEmail() {
		return this.cdEmail;
	}

	public void setCdEmail(String cdEmail) {
		this.cdEmail = cdEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_admissao", length = 0)
	public Date getDtAdmissao() {
		return this.dtAdmissao;
	}

	public void setDtAdmissao(Date dtAdmissao) {
		this.dtAdmissao = dtAdmissao;
	}

	@Column(name = "Endereco", length = 100)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "Numero")
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "Complemento", length = 30)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "Bairro", length = 30)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "Cidade", length = 40)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "UF", length = 2)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	@Column(name = "Pais", length = 40)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "CEP", length = 10)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "nr_tel", precision = 14, scale = 0)
	public Long getNrTel() {
		return this.nrTel;
	}

	public void setNrTel(Long nrTel) {
		this.nrTel = nrTel;
	}

	@Column(name = "nr_celular", precision = 14, scale = 0)
	public Long getNrCelular() {
		return this.nrCelular;
	}

	public void setNrCelular(Long nrCelular) {
		this.nrCelular = nrCelular;
	}

	@Column(name = "nr_ident", length = 20)
	public String getNrIdent() {
		return this.nrIdent;
	}

	public void setNrIdent(String nrIdent) {
		this.nrIdent = nrIdent;
	}

}
