package br.telehand.model;

// Generated 09/04/2014 16:06:53 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbDiasId generated by hbm2java
 */
@Embeddable
public class TbDiasId implements java.io.Serializable {

	private int idJanela;
	private int cdDia;
	private int cdSemana;

	public TbDiasId() {
	}

	public TbDiasId(int idJanela, int cdDia, int cdSemana) {
		this.idJanela = idJanela;
		this.cdDia = cdDia;
		this.cdSemana = cdSemana;
	}

	@Column(name = "Id_janela", nullable = false)
	public int getIdJanela() {
		return this.idJanela;
	}

	public void setIdJanela(int idJanela) {
		this.idJanela = idJanela;
	}

	@Column(name = "Cd_dia", nullable = false)
	public int getCdDia() {
		return this.cdDia;
	}

	public void setCdDia(int cdDia) {
		this.cdDia = cdDia;
	}

	@Column(name = "cd_semana", nullable = false)
	public int getCdSemana() {
		return this.cdSemana;
	}

	public void setCdSemana(int cdSemana) {
		this.cdSemana = cdSemana;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbDiasId))
			return false;
		TbDiasId castOther = (TbDiasId) other;

		return (this.getIdJanela() == castOther.getIdJanela())
				&& (this.getCdDia() == castOther.getCdDia())
				&& (this.getCdSemana() == castOther.getCdSemana());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdJanela();
		result = 37 * result + this.getCdDia();
		result = 37 * result + this.getCdSemana();
		return result;
	}

}
