package br.telehand.model;

// Generated 27/03/2014 16:20:36 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbEquipe generated by hbm2java
 */
@Entity
@Table(name = "tb_equipe", catalog = "db_sge")
public class TbEquipe implements java.io.Serializable {

	private Integer idEquipe;
	private TbServico tbServico;
	private int nrMatricula;
	private int nrSmarthfone;
	private int nrCepInicial;
	private int nrCepFinal;
	private Set tbTecAuxiliareses = new HashSet(0);
	private Set tbBloqueios = new HashSet(0);
	private Set tbAgendas = new HashSet(0);

	public TbEquipe() {
	}

	public TbEquipe(TbServico tbServico, int nrMatricula, int nrSmarthfone,
			int nrCepInicial, int nrCepFinal) {
		this.tbServico = tbServico;
		this.nrMatricula = nrMatricula;
		this.nrSmarthfone = nrSmarthfone;
		this.nrCepInicial = nrCepInicial;
		this.nrCepFinal = nrCepFinal;
	}

	public TbEquipe(TbServico tbServico, int nrMatricula, int nrSmarthfone,
			int nrCepInicial, int nrCepFinal, Set tbTecAuxiliareses,
			Set tbBloqueios, Set tbAgendas) {
		this.tbServico = tbServico;
		this.nrMatricula = nrMatricula;
		this.nrSmarthfone = nrSmarthfone;
		this.nrCepInicial = nrCepInicial;
		this.nrCepFinal = nrCepFinal;
		this.tbTecAuxiliareses = tbTecAuxiliareses;
		this.tbBloqueios = tbBloqueios;
		this.tbAgendas = tbAgendas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_equipe", unique = true, nullable = false)
	public Integer getIdEquipe() {
		return this.idEquipe;
	}

	public void setIdEquipe(Integer idEquipe) {
		this.idEquipe = idEquipe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_servico", nullable = false)
	public TbServico getTbServico() {
		return this.tbServico;
	}

	public void setTbServico(TbServico tbServico) {
		this.tbServico = tbServico;
	}

	@Column(name = "Nr_matricula", nullable = false)
	public int getNrMatricula() {
		return this.nrMatricula;
	}

	public void setNrMatricula(int nrMatricula) {
		this.nrMatricula = nrMatricula;
	}

	@Column(name = "Nr_smarthfone", nullable = false)
	public int getNrSmarthfone() {
		return this.nrSmarthfone;
	}

	public void setNrSmarthfone(int nrSmarthfone) {
		this.nrSmarthfone = nrSmarthfone;
	}

	@Column(name = "Nr_cep_inicial", nullable = false)
	public int getNrCepInicial() {
		return this.nrCepInicial;
	}

	public void setNrCepInicial(int nrCepInicial) {
		this.nrCepInicial = nrCepInicial;
	}

	@Column(name = "Nr_cep_final", nullable = false)
	public int getNrCepFinal() {
		return this.nrCepFinal;
	}

	public void setNrCepFinal(int nrCepFinal) {
		this.nrCepFinal = nrCepFinal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbEquipe")
	public Set<TbTecAuxiliares> getTbTecAuxiliareses() {
		return this.tbTecAuxiliareses;
	}

	public void setTbTecAuxiliareses(Set<TbTecAuxiliares> tbTecAuxiliareses) {
		this.tbTecAuxiliareses = tbTecAuxiliareses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbEquipe")
	public Set<TbBloqueio> getTbBloqueios() {
		return this.tbBloqueios;
	}

	public void setTbBloqueios(Set<TbBloqueio> tbBloqueios) {
		this.tbBloqueios = tbBloqueios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbEquipe")
	public Set<TbAgenda> getTbAgendas() {
		return this.tbAgendas;
	}

	public void setTbAgendas(Set<TbAgenda> tbAgendas) {
		this.tbAgendas = tbAgendas;
	}

}
