package br.telehand.model;

// Generated 27/03/2014 16:20:36 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbLogId generated by hbm2java
 */
@Embeddable
public class TbLogId implements java.io.Serializable {

	private int nrMatricula;
	private Date dtOperacao;

	public TbLogId() {
	}

	public TbLogId(int nrMatricula, Date dtOperacao) {
		this.nrMatricula = nrMatricula;
		this.dtOperacao = dtOperacao;
	}

	@Column(name = "Nr_matricula", nullable = false)
	public int getNrMatricula() {
		return this.nrMatricula;
	}

	public void setNrMatricula(int nrMatricula) {
		this.nrMatricula = nrMatricula;
	}

	@Column(name = "Dt_operacao", nullable = false, length = 0)
	public Date getDtOperacao() {
		return this.dtOperacao;
	}

	public void setDtOperacao(Date dtOperacao) {
		this.dtOperacao = dtOperacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbLogId))
			return false;
		TbLogId castOther = (TbLogId) other;

		return (this.getNrMatricula() == castOther.getNrMatricula())
				&& ((this.getDtOperacao() == castOther.getDtOperacao()) || (this
						.getDtOperacao() != null
						&& castOther.getDtOperacao() != null && this
						.getDtOperacao().equals(castOther.getDtOperacao())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNrMatricula();
		result = 37
				* result
				+ (getDtOperacao() == null ? 0 : this.getDtOperacao()
						.hashCode());
		return result;
	}

}
