package br.telehand.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TbLogin generated by hbm2java
 */
@Entity
@Table(name = "tb_login", catalog = "db_sge")
public class TbLogin implements java.io.Serializable {

	private TbLoginId id;

	public TbLogin() {
	}

	public TbLogin(TbLoginId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrMatricula", column = @Column(name = "Nr_matricula", nullable = false)),
			@AttributeOverride(name = "cdUsuario", column = @Column(name = "Cd_USUARIO", nullable = false, length = 1)),
			@AttributeOverride(name = "cdSenha", column = @Column(name = "CD_SENHA", nullable = false, length = 4)) })
	public TbLoginId getId() {
		return this.id;
	}

	public void setId(TbLoginId id) {
		this.id = id;
	}

}
