package br.telehand.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbReporteId generated by hbm2java
 */
@Embeddable
public class TbReporteId implements java.io.Serializable {

	private int idAtendimento;
	private char cdStatus;
	private Date dtReporte;

	public TbReporteId() {
	}

	public TbReporteId(int idAtendimento, char cdStatus, Date dtReporte) {
		this.idAtendimento = idAtendimento;
		this.cdStatus = cdStatus;
		this.dtReporte = dtReporte;
	}

	@Column(name = "Id_atendimento", nullable = false)
	public int getIdAtendimento() {
		return this.idAtendimento;
	}

	public void setIdAtendimento(int idAtendimento) {
		this.idAtendimento = idAtendimento;
	}

	@Column(name = "Cd_status", nullable = false, length = 1)
	public char getCdStatus() {
		return this.cdStatus;
	}

	public void setCdStatus(char cdStatus) {
		this.cdStatus = cdStatus;
	}

	@Column(name = "Dt_reporte", nullable = false, length = 0)
	public Date getDtReporte() {
		return this.dtReporte;
	}

	public void setDtReporte(Date dtReporte) {
		this.dtReporte = dtReporte;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbReporteId))
			return false;
		TbReporteId castOther = (TbReporteId) other;

		return (this.getIdAtendimento() == castOther.getIdAtendimento())
				&& (this.getCdStatus() == castOther.getCdStatus())
				&& ((this.getDtReporte() == castOther.getDtReporte()) || (this
						.getDtReporte() != null
						&& castOther.getDtReporte() != null && this
						.getDtReporte().equals(castOther.getDtReporte())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAtendimento();
		result = 37 * result + this.getCdStatus();
		result = 37 * result
				+ (getDtReporte() == null ? 0 : this.getDtReporte().hashCode());
		return result;
	}

}
