package br.telehand.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbReporte generated by hbm2java
 */
@Entity
@Table(name="tb_reporte"
    ,catalog="db_sge"
)
public class TbReporte  implements java.io.Serializable {


     private TbReporteId id;
     private TbAtendimento tbAtendimento;
     private Character cdPendencia;
     private String txLongitude;
     private String txLatitude;
     private Integer nrMatricula;

    public TbReporte() {
    }

	
    public TbReporte(TbReporteId id, TbAtendimento tbAtendimento) {
        this.id = id;
        this.tbAtendimento = tbAtendimento;
    }
    public TbReporte(TbReporteId id, TbAtendimento tbAtendimento, Character cdPendencia, String txLongitude, String txLatitude, Integer nrMatricula) {
       this.id = id;
       this.tbAtendimento = tbAtendimento;
       this.cdPendencia = cdPendencia;
       this.txLongitude = txLongitude;
       this.txLatitude = txLatitude;
       this.nrMatricula = nrMatricula;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idAtendimento", column=@Column(name="Id_atendimento", nullable=false) ), 
        @AttributeOverride(name="cdStatus", column=@Column(name="Cd_status", nullable=false, length=1) ), 
        @AttributeOverride(name="dtReporte", column=@Column(name="Dt_reporte", nullable=false, length=0) ) } )
    public TbReporteId getId() {
        return this.id;
    }
    
    public void setId(TbReporteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Id_atendimento", nullable=false, insertable=false, updatable=false)
    public TbAtendimento getTbAtendimento() {
        return this.tbAtendimento;
    }
    
    public void setTbAtendimento(TbAtendimento tbAtendimento) {
        this.tbAtendimento = tbAtendimento;
    }

    
    @Column(name="Cd_pendencia", length=1)
    public Character getCdPendencia() {
        return this.cdPendencia;
    }
    
    public void setCdPendencia(Character cdPendencia) {
        this.cdPendencia = cdPendencia;
    }

    
    @Column(name="Tx_longitude", length=8)
    public String getTxLongitude() {
        return this.txLongitude;
    }
    
    public void setTxLongitude(String txLongitude) {
        this.txLongitude = txLongitude;
    }

    
    @Column(name="Tx_latitude", length=8)
    public String getTxLatitude() {
        return this.txLatitude;
    }
    
    public void setTxLatitude(String txLatitude) {
        this.txLatitude = txLatitude;
    }

    
    @Column(name="Nr_matricula")
    public Integer getNrMatricula() {
        return this.nrMatricula;
    }
    
    public void setNrMatricula(Integer nrMatricula) {
        this.nrMatricula = nrMatricula;
    }




}


