package br.telehand.model;

// Generated 27/03/2014 16:20:36 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TbRhDisponibilidade generated by hbm2java
 */
@Entity
@Table(name = "tb_rh_disponibilidade", catalog = "db_sge")
public class TbRhDisponibilidade implements java.io.Serializable {

	private int nrMatricula;
	private TbRh tbRh;
	private Date dtInicioIndisp;
	private Date dtFimIndisp;

	public TbRhDisponibilidade() {
	}

	public TbRhDisponibilidade(TbRh tbRh, Date dtInicioIndisp, Date dtFimIndisp) {
		this.tbRh = tbRh;
		this.dtInicioIndisp = dtInicioIndisp;
		this.dtFimIndisp = dtFimIndisp;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tbRh"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "nr_matricula", unique = true, nullable = false)
	public int getNrMatricula() {
		return this.nrMatricula;
	}

	public void setNrMatricula(int nrMatricula) {
		this.nrMatricula = nrMatricula;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public TbRh getTbRh() {
		return this.tbRh;
	}

	public void setTbRh(TbRh tbRh) {
		this.tbRh = tbRh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_inicio_indisp", nullable = false, length = 0)
	public Date getDtInicioIndisp() {
		return this.dtInicioIndisp;
	}

	public void setDtInicioIndisp(Date dtInicioIndisp) {
		this.dtInicioIndisp = dtInicioIndisp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_fim_indisp", nullable = false, length = 0)
	public Date getDtFimIndisp() {
		return this.dtFimIndisp;
	}

	public void setDtFimIndisp(Date dtFimIndisp) {
		this.dtFimIndisp = dtFimIndisp;
	}

}
