package br.telehand.model;

// Generated 27/03/2014 16:20:36 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TbRh generated by hbm2java
 */
@Entity
@Table(name = "tb_rh", catalog = "db_sge")
public class TbRh implements java.io.Serializable {

	private int nrMatricula;
	private Long cpf;
	private String nmEmpregado;
	private String cdEmail;
	private TbRhDisponibilidade tbRhDisponibilidade;

	public TbRh() {
	}

	public TbRh(int nrMatricula, String nmEmpregado) {
		this.nrMatricula = nrMatricula;
		this.nmEmpregado = nmEmpregado;
	}

	public TbRh(int nrMatricula, Long cpf, String nmEmpregado, String cdEmail,
			TbRhDisponibilidade tbRhDisponibilidade) {
		this.nrMatricula = nrMatricula;
		this.cpf = cpf;
		this.nmEmpregado = nmEmpregado;
		this.cdEmail = cdEmail;
		this.tbRhDisponibilidade = tbRhDisponibilidade;
	}

	@Id
	@Column(name = "nr_matricula", unique = true, nullable = false)
	public int getNrMatricula() {
		return this.nrMatricula;
	}

	public void setNrMatricula(int nrMatricula) {
		this.nrMatricula = nrMatricula;
	}

	@Column(name = "cpf", precision = 11, scale = 0)
	public Long getCpf() {
		return this.cpf;
	}

	public void setCpf(Long cpf) {
		this.cpf = cpf;
	}

	@Column(name = "nm_empregado", nullable = false, length = 20)
	public String getNmEmpregado() {
		return this.nmEmpregado;
	}

	public void setNmEmpregado(String nmEmpregado) {
		this.nmEmpregado = nmEmpregado;
	}

	@Column(name = "cd_email")
	public String getCdEmail() {
		return this.cdEmail;
	}

	public void setCdEmail(String cdEmail) {
		this.cdEmail = cdEmail;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "tbRh")
	public TbRhDisponibilidade getTbRhDisponibilidade() {
		return this.tbRhDisponibilidade;
	}

	public void setTbRhDisponibilidade(TbRhDisponibilidade tbRhDisponibilidade) {
		this.tbRhDisponibilidade = tbRhDisponibilidade;
	}

}
