package br.telehand.model;

// Generated 27/03/2014 16:20:36 by Hibernate Tools 4.0.0

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbServico generated by hbm2java
 */
@Entity
@Table(name = "tb_servico", catalog = "db_sge")
public class TbServico implements java.io.Serializable {

	private Integer idServico;
	private String nmServico;
	private Integer qtInicio;
	private Integer qtFim;
	private Integer qtEmp;
	private Date dtVigencia;
	private Set tbJanelas = new HashSet(0);
	private Set tbOses = new HashSet(0);
	private Set tbEquipes = new HashSet(0);

	public TbServico() {
	}

	public TbServico(String nmServico, Integer qtInicio, Integer qtFim,
			Integer qtEmp, Date dtVigencia, Set tbJanelas, Set tbOses,
			Set tbEquipes) {
		this.nmServico = nmServico;
		this.qtInicio = qtInicio;
		this.qtFim = qtFim;
		this.qtEmp = qtEmp;
		this.dtVigencia = dtVigencia;
		this.tbJanelas = tbJanelas;
		this.tbOses = tbOses;
		this.tbEquipes = tbEquipes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_servico", unique = true, nullable = false)
	public Integer getIdServico() {
		return this.idServico;
	}

	public void setIdServico(Integer idServico) {
		this.idServico = idServico;
	}

	@Column(name = "Nm_servico", length = 100)
	public String getNmServico() {
		return this.nmServico;
	}

	public void setNmServico(String nmServico) {
		this.nmServico = nmServico;
	}

	@Column(name = "Qt_inicio")
	public Integer getQtInicio() {
		return this.qtInicio;
	}

	public void setQtInicio(Integer qtInicio) {
		this.qtInicio = qtInicio;
	}

	@Column(name = "Qt_fim")
	public Integer getQtFim() {
		return this.qtFim;
	}

	public void setQtFim(Integer qtFim) {
		this.qtFim = qtFim;
	}

	@Column(name = "Qt_emp")
	public Integer getQtEmp() {
		return this.qtEmp;
	}

	public void setQtEmp(Integer qtEmp) {
		this.qtEmp = qtEmp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Dt_vigencia", length = 0)
	public Date getDtVigencia() {
		return this.dtVigencia;
	}

	public void setDtVigencia(Date dtVigencia) {
		this.dtVigencia = dtVigencia;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tbServico")
	public Set<TbJanela> getTbJanelas() {
		return this.tbJanelas;
	}

	public void setTbJanelas(Set<TbJanela> tbJanelas) {
		this.tbJanelas = tbJanelas;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tbServico")
	public Set<TbOs> getTbOses() {
		return this.tbOses;
	}

	public void setTbOses(Set<TbOs> tbOses) {
		this.tbOses = tbOses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tbServico")
	public Set<TbEquipe> getTbEquipes() {
		return this.tbEquipes;
	}

	public void setTbEquipes(Set<TbEquipe> tbEquipes) {
		this.tbEquipes = tbEquipes;
	}
	
	public static String formateDate(String dateString) {
	    Date date;
	    String formattedDate = "";
	    try {
	        date = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss",Locale.getDefault()).parse(dateString);
	        formattedDate = new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).format(date);
	    } catch (ParseException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }

	    return formattedDate;
	}

}
