package br.telehand.model;

// Generated 27/03/2014 16:20:36 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbTecAuxiliaresId generated by hbm2java
 */
@Embeddable
public class TbTecAuxiliaresId implements java.io.Serializable {

	private int idEquipe;
	private int nrMatricula;

	public TbTecAuxiliaresId() {
	}

	public TbTecAuxiliaresId(int idEquipe, int nrMatricula) {
		this.idEquipe = idEquipe;
		this.nrMatricula = nrMatricula;
	}

	@Column(name = "Id_equipe", nullable = false)
	public int getIdEquipe() {
		return this.idEquipe;
	}

	public void setIdEquipe(int idEquipe) {
		this.idEquipe = idEquipe;
	}

	@Column(name = "Nr_matricula", nullable = false)
	public int getNrMatricula() {
		return this.nrMatricula;
	}

	public void setNrMatricula(int nrMatricula) {
		this.nrMatricula = nrMatricula;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbTecAuxiliaresId))
			return false;
		TbTecAuxiliaresId castOther = (TbTecAuxiliaresId) other;

		return (this.getIdEquipe() == castOther.getIdEquipe())
				&& (this.getNrMatricula() == castOther.getNrMatricula());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEquipe();
		result = 37 * result + this.getNrMatricula();
		return result;
	}

}
