package br.telehand.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwAgendaComAgendamento generated by hbm2java
 */
@Entity
@Table(name = "vw_agenda_com_agendamento", catalog = "db_sge")
public class VwAgendaComAgendamento implements java.io.Serializable {

	private VwAgendaComAgendamentoId id;

	public VwAgendaComAgendamento() {
	}

	public VwAgendaComAgendamento(VwAgendaComAgendamentoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idServico", column = @Column(name = "id_servico", nullable = false)),
			@AttributeOverride(name = "idJanela", column = @Column(name = "id_janela", nullable = false)),
			@AttributeOverride(name = "idEquipe", column = @Column(name = "id_equipe", nullable = false)),
			@AttributeOverride(name = "hrInicial", column = @Column(name = "Hr_inicial", nullable = false, length = 0)),
			@AttributeOverride(name = "hrFinal", column = @Column(name = "Hr_final", nullable = false, length = 0)),
			@AttributeOverride(name = "idAtendimento", column = @Column(name = "id_atendimento", nullable = false)),
			@AttributeOverride(name = "data", column = @Column(name = "data", nullable = false, length = 19)),
			@AttributeOverride(name = "nrMatriculaTecnico", column = @Column(name = "NrMatriculaTecnico", nullable = false)),
			@AttributeOverride(name = "cdStatus", column = @Column(name = "cd_status", nullable = false)),
			@AttributeOverride(name = "idOs", column = @Column(name = "Id_OS", nullable = false)) })
	public VwAgendaComAgendamentoId getId() {
		return this.id;
	}

	public void setId(VwAgendaComAgendamentoId id) {
		this.id = id;
	}

}
