package br.telehand.model;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwAgendaSemAgendamentoId generated by hbm2java
 */
@Embeddable
public class VwAgendaSemAgendamentoId implements java.io.Serializable {

	private int idServico;
	private int idJanela;
	private int idEquipe;
	private Date hrInicial;
	private Date hrFinal;
	private int cdDia;
	private int cdSemana;
	private Date anoMesDia;
	private int nrMatriculaTecnico;

	public VwAgendaSemAgendamentoId() {
	}

	public VwAgendaSemAgendamentoId(int idServico, int idJanela, int idEquipe,
			Date hrInicial, Date hrFinal, int cdDia, int cdSemana,
			int nrMatriculaTecnico) {
		this.idServico = idServico;
		this.idJanela = idJanela;
		this.idEquipe = idEquipe;
		this.hrInicial = hrInicial;
		this.hrFinal = hrFinal;
		this.cdDia = cdDia;
		this.cdSemana = cdSemana;
		this.nrMatriculaTecnico = nrMatriculaTecnico;
	}

	public VwAgendaSemAgendamentoId(int idServico, int idJanela, int idEquipe,
			Date hrInicial, Date hrFinal, int cdDia, int cdSemana,
			Date anoMesDia, int nrMatriculaTecnico) {
		this.idServico = idServico;
		this.idJanela = idJanela;
		this.idEquipe = idEquipe;
		this.hrInicial = hrInicial;
		this.hrFinal = hrFinal;
		this.cdDia = cdDia;
		this.cdSemana = cdSemana;
		this.anoMesDia = anoMesDia;
		this.nrMatriculaTecnico = nrMatriculaTecnico;
	}

	@Column(name = "id_servico", nullable = false)
	public int getIdServico() {
		return this.idServico;
	}

	public void setIdServico(int idServico) {
		this.idServico = idServico;
	}

	@Column(name = "id_janela", nullable = false)
	public int getIdJanela() {
		return this.idJanela;
	}

	public void setIdJanela(int idJanela) {
		this.idJanela = idJanela;
	}

	@Column(name = "id_equipe", nullable = false)
	public int getIdEquipe() {
		return this.idEquipe;
	}

	public void setIdEquipe(int idEquipe) {
		this.idEquipe = idEquipe;
	}

	@Column(name = "Hr_inicial", nullable = false, length = 0)
	public Date getHrInicial() {
		return this.hrInicial;
	}

	public void setHrInicial(Date hrInicial) {
		this.hrInicial = hrInicial;
	}

	@Column(name = "Hr_final", nullable = false, length = 0)
	public Date getHrFinal() {
		return this.hrFinal;
	}

	public void setHrFinal(Date hrFinal) {
		this.hrFinal = hrFinal;
	}

	@Column(name = "cd_dia", nullable = false)
	public int getCdDia() {
		return this.cdDia;
	}

	public void setCdDia(int cdDia) {
		this.cdDia = cdDia;
	}

	@Column(name = "cd_semana", nullable = false)
	public int getCdSemana() {
		return this.cdSemana;
	}

	public void setCdSemana(int cdSemana) {
		this.cdSemana = cdSemana;
	}

	@Column(name = "ano_mes_dia", length = 0)
	public Date getAnoMesDia() {
		return this.anoMesDia;
	}

	public void setAnoMesDia(Date anoMesDia) {
		this.anoMesDia = anoMesDia;
	}

	@Column(name = "NrMatriculaTecnico", nullable = false)
	public int getNrMatriculaTecnico() {
		return this.nrMatriculaTecnico;
	}

	public void setNrMatriculaTecnico(int nrMatriculaTecnico) {
		this.nrMatriculaTecnico = nrMatriculaTecnico;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwAgendaSemAgendamentoId))
			return false;
		VwAgendaSemAgendamentoId castOther = (VwAgendaSemAgendamentoId) other;

		return (this.getIdServico() == castOther.getIdServico())
				&& (this.getIdJanela() == castOther.getIdJanela())
				&& (this.getIdEquipe() == castOther.getIdEquipe())
				&& ((this.getHrInicial() == castOther.getHrInicial()) || (this
						.getHrInicial() != null
						&& castOther.getHrInicial() != null && this
						.getHrInicial().equals(castOther.getHrInicial())))
				&& ((this.getHrFinal() == castOther.getHrFinal()) || (this
						.getHrFinal() != null && castOther.getHrFinal() != null && this
						.getHrFinal().equals(castOther.getHrFinal())))
				&& (this.getCdDia() == castOther.getCdDia())
				&& (this.getCdSemana() == castOther.getCdSemana())
				&& ((this.getAnoMesDia() == castOther.getAnoMesDia()) || (this
						.getAnoMesDia() != null
						&& castOther.getAnoMesDia() != null && this
						.getAnoMesDia().equals(castOther.getAnoMesDia())))
				&& (this.getNrMatriculaTecnico() == castOther
						.getNrMatriculaTecnico());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdServico();
		result = 37 * result + this.getIdJanela();
		result = 37 * result + this.getIdEquipe();
		result = 37 * result
				+ (getHrInicial() == null ? 0 : this.getHrInicial().hashCode());
		result = 37 * result
				+ (getHrFinal() == null ? 0 : this.getHrFinal().hashCode());
		result = 37 * result + this.getCdDia();
		result = 37 * result + this.getCdSemana();
		result = 37 * result
				+ (getAnoMesDia() == null ? 0 : this.getAnoMesDia().hashCode());
		result = 37 * result + this.getNrMatriculaTecnico();
		return result;
	}

}
