package br.telehand.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwAgendaComAgendamentoId generated by hbm2java
 */
@Embeddable
public class VwAgendaComAgendamentoId implements java.io.Serializable {

	private int idServico;
	private int idJanela;
	private int idEquipe;
	private Date hrInicial;
	private Date hrFinal;
	private long idAtendimento;
	private String data;
	private int nrMatriculaTecnico;
	private int idOs;
	private String cdStatus;


	public VwAgendaComAgendamentoId() {
	}

	public VwAgendaComAgendamentoId(int idServico, int idJanela, int idEquipe,
			Date hrInicial, Date hrFinal, long idAtendimento, String data,
			int nrMatriculaTecnico, int idOs, String cdStatus) {
		this.idServico = idServico;
		this.idJanela = idJanela;
		this.idEquipe = idEquipe;
		this.hrInicial = hrInicial;
		this.hrFinal = hrFinal;
		this.idAtendimento = idAtendimento;
		this.data = data;
		this.nrMatriculaTecnico = nrMatriculaTecnico;
		this.idOs = idOs;
		this.cdStatus = cdStatus;
	}

	@Column(name = "id_servico", nullable = false)
	public int getIdServico() {
		return this.idServico;
	}

	public void setIdServico(int idServico) {
		this.idServico = idServico;
	}

	@Column(name = "id_janela", nullable = false)
	public int getIdJanela() {
		return this.idJanela;
	}

	public void setIdJanela(int idJanela) {
		this.idJanela = idJanela;
	}

	@Column(name = "id_equipe", nullable = false)
	public int getIdEquipe() {
		return this.idEquipe;
	}

	public void setIdEquipe(int idEquipe) {
		this.idEquipe = idEquipe;
	}

	@Column(name = "Hr_inicial", nullable = false, length = 0)
	public Date getHrInicial() {
		return this.hrInicial;
	}

	public void setHrInicial(Date hrInicial) {
		this.hrInicial = hrInicial;
	}

	@Column(name = "Hr_final", nullable = false, length = 0)
	public Date getHrFinal() {
		return this.hrFinal;
	}

	public void setHrFinal(Date hrFinal) {
		this.hrFinal = hrFinal;
	}

	@Column(name = "id_atendimento", nullable = false)
	public long getIdAtendimento() {
		return this.idAtendimento;
	}

	public void setIdAtendimento(long idAtendimento) {
		this.idAtendimento = idAtendimento;
	}

	@Column(name = "data", nullable = false, length = 19)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "NrMatriculaTecnico", nullable = false)
	public int getNrMatriculaTecnico() {
		return this.nrMatriculaTecnico;
	}

	public void setNrMatriculaTecnico(int nrMatriculaTecnico) {
		this.nrMatriculaTecnico = nrMatriculaTecnico;
	}

	@Column(name = "Id_OS", nullable = false)
	public int getIdOs() {
		return this.idOs;
	}

	public void setIdOs(int idOs) {
		this.idOs = idOs;
	}
	
	@Column(name = "cd_status", nullable = false)
	public String getCdStatus() {
		return this.cdStatus;
	}

	public void setCdStatus(String cdStatus) {
		this.cdStatus = cdStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwAgendaComAgendamentoId))
			return false;
		VwAgendaComAgendamentoId castOther = (VwAgendaComAgendamentoId) other;

		return (this.getIdServico() == castOther.getIdServico())
				&& (this.getIdJanela() == castOther.getIdJanela())
				&& (this.getIdEquipe() == castOther.getIdEquipe())
				&& ((this.getHrInicial() == castOther.getHrInicial()) || (this
						.getHrInicial() != null
						&& castOther.getHrInicial() != null && this
						.getHrInicial().equals(castOther.getHrInicial())))
				&& ((this.getHrFinal() == castOther.getHrFinal()) || (this
						.getHrFinal() != null && castOther.getHrFinal() != null && this
						.getHrFinal().equals(castOther.getHrFinal())))
				&& (this.getIdAtendimento() == castOther.getIdAtendimento())
				&& ((this.getData() == castOther.getData()) || (this.getData() != null
						&& castOther.getData() != null && this.getData()
						.equals(castOther.getData())))
				&& (this.getNrMatriculaTecnico() == castOther
						.getNrMatriculaTecnico())
				&& (this.getCdStatus() == castOther
						.getCdStatus())
				&& (this.getCdStatus() == castOther.getCdStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdServico();
		result = 37 * result + this.getIdJanela();
		result = 37 * result + this.getIdEquipe();
		result = 37 * result
				+ (getHrInicial() == null ? 0 : this.getHrInicial().hashCode());
		result = 37 * result
				+ (getHrFinal() == null ? 0 : this.getHrFinal().hashCode());
		result = 37 * result + (int) this.getIdAtendimento();
		result = 37 * result
				+ (getData() == null ? 0 : this.getData().hashCode());
		result = 37 * result + this.getNrMatriculaTecnico();
		result = 37 * result + this.getIdOs();
		return result;
	}

}
