package br.telehand.model;

// Generated 27/03/2014 16:20:36 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwAlmoxarife generated by hbm2java
 */
@Entity
@Table(name = "vw_almoxarife", catalog = "db_sge")
public class VwAlmoxarife implements java.io.Serializable {

	private VwAlmoxarifeId id;

	public VwAlmoxarife() {
	}

	public VwAlmoxarife(VwAlmoxarifeId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idServico", column = @Column(name = "ID_SERVICO", nullable = false)),
			@AttributeOverride(name = "cdKit", column = @Column(name = "CD_KIT", nullable = false)) })
	public VwAlmoxarifeId getId() {
		return this.id;
	}

	public void setId(VwAlmoxarifeId id) {
		this.id = id;
	}

}
