package br.telehand.model;

// Generated 27/03/2014 16:20:36 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwAlmoxarifeId generated by hbm2java
 */
@Embeddable
public class VwAlmoxarifeId implements java.io.Serializable {

	private int idServico;
	private int cdKit;

	public VwAlmoxarifeId() {
	}

	public VwAlmoxarifeId(int idServico, int cdKit) {
		this.idServico = idServico;
		this.cdKit = cdKit;
	}

	@Column(name = "ID_SERVICO", nullable = false)
	public int getIdServico() {
		return this.idServico;
	}

	public void setIdServico(int idServico) {
		this.idServico = idServico;
	}

	@Column(name = "CD_KIT", nullable = false)
	public int getCdKit() {
		return this.cdKit;
	}

	public void setCdKit(int cdKit) {
		this.cdKit = cdKit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwAlmoxarifeId))
			return false;
		VwAlmoxarifeId castOther = (VwAlmoxarifeId) other;

		return (this.getIdServico() == castOther.getIdServico())
				&& (this.getCdKit() == castOther.getCdKit());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdServico();
		result = 37 * result + this.getCdKit();
		return result;
	}

}
